config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, class_name: "Admin", controllers: { sessions: "admin/sessions" }
  devise_for :users, class_name: "User", controllers: { omniauth_callbacks: "omniauth_callbacks", 
  	registrations: "registrations", sessions: "sessions" }

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root to: "home#index"

  resources :foods do
  	member do
  		get :manage_dish
      get :price_dish
      get :ad_dish
      get :will_be_served_dish
      get :photos_dish
      get :about_place_dish
      get :ads_dish
      get :location_dish
  	end
  end

end

app/views/shared/_flash_messages.html.erb
<% if flash[:alert].present? %>
	<div class="alert alert-danger"><%= flash[:alert].html_safe %></div>
<% end %>
<% if flash[:notice].present? %>
	<div class="alert alert-success"><%= flash[:notice].html_safe %></div>
<% end %>
<% if flash[:info].present? %>
	<div class="alert alert-info"><%= flash[:info].html_safe %></div>
<% end %>

app/views/shared/_left_side.html.erb
<div class="left-side">
  <h2><%= t('manage_dish.basic') %></h2>
  <ul>
    <li>
      <%= link_to t('manage_dish.calendar'), manage_dish_food_path(@food) %>
      <i class="material-icons">&#xE145;</i>
    </li>
    <li>
      <%= link_to t('manage_dish.price'), price_dish_food_path(@food) %>
      <i class="material-icons">&#xE145;</i>
    </li>
  </ul>

  <h2><%=  t('manage_dish.menu') %></h2>
  <ul>
    <li>
      <%= link_to t('manage_dish.ad'), ad_dish_food_path(@food) %>
      <i class="material-icons">&#xE145;</i>
    </li>
    <li>
      <%= link_to t('manage_dish.will_be_served'), will_be_served_dish_food_path(@food) %>
      <i class="material-icons">&#xE145;</i>
    </li>
    <li>
      <%= link_to t('manage_dish.photos'), photos_dish_food_path(@food) %>
      <i class="material-icons">&#xE145;</i>
    </li>
  </ul>

  <h2><%=  t('manage_dish.settings') %></h2>
  <ul>
    <li>
      <%= link_to t('manage_dish.about_place'), about_place_dish_food_path(@food) %>
      <i class="material-icons">&#xE145;</i>
    </li>
    <li>
      <%= link_to t('manage_dish.ads'), ads_dish_food_path(@food) %>
      <i class="material-icons">&#xE145;</i>
    </li>
    <li>
      <%= link_to t('manage_dish.location'), manage_dish_food_path(@food) %>
      <i class="material-icons">&#xE145;</i>
    </li>
  </ul>

</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-full navbar-dark bg-inverse">
  <button class="navbar-toggler hidden-sm-up" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar2">
    &#9776;
  </button>
  <%= image_tag('dinneer-logo.png', class: 'logo') %>
  <div class="collapse navbar-toggleable-xs" id="exCollapsingNavbar2">
    <ul class="nav navbar-nav pull-xs-right">
      <li class="nav-item active">
        <a class="nav-link" href="#">Como funciona? <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="#">Blog</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="#">Ajuda</a>
      </li>

      <% if user_signed_in? %>
        <li class="nav-item active">
          <a class="nav-link" href="#"><%= current_user.email %></a>
        </li>
      <% else %>
        <li class="nav-item active">
          <a class="nav-link" href="#">Cadastre-se</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" data-toggle="modal" data-target=".bd-login-modal-sm" href="#">Entrar</a>
        </li>
      <% end -%>
    </ul>
  </div>
</nav>


<div class="modal fade bd-login-modal-sm" tabindex="-1" role="dialog" aria-labelledby="Login" 
  aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content-signup">

        <div class="modal-body">
            
          <%= form_for(:user, as: "user", url: session_path(:user), class: '') do |f| %>
            
            <div class="form-group">
              <%= link_to 'Fazer login com o facebook', user_facebook_omniauth_authorize_path, class: 'btn btn-primary btn-facebook' %>
            </div>
            
            <div class="form-group">
              <%= f.email_field :email, class: 'form-control', autofocus: true, 
                placeholder: 'E-mail' %>
            </div>

            <div class="form-group">
              <%= f.password_field :password, class: 'form-control', autocomplete: "off", 
                placeholder: 'Password' %>
            </div>

            <div class="form-group">
              <%= f.submit "Entrar", class: 'btn btn-primary' %>
            </div>
          <% end %>
        </div>
    </div>
  </div>
</div>