config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, class_name: "Admin", controllers: { sessions: "admin/sessions" }
  devise_for :users, class_name: "User", controllers: { omniauth_callbacks: "omniauth_callbacks", 
  	registrations: "registrations", sessions: "sessions" }

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root to: "home#index"

  resources :foods do
  	member do
  		get :manage_dish
      get :price_dish
      get :ad_dish
      get :will_be_served_dish
      get :photos_dish
      get :about_place_dish
      get :ads_dish
      get :location_dish
  	end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	skip_before_filter :verify_authenticity_token
  skip_before_filter :render_unauthorized
  skip_before_filter :authenticate_user!

	def index
	end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<section class="header">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 text-xs-center center-block">
        <h1 >Sinta-se em casa</h1>
        <h3>Dinneer conecta pessoas que amam novas experiências gastronômicas com anfitriões que oferecem almoços e jantares exclusivos em suas casas em 22 países</h3>
        <%= link_to 'Torna-se um anfitrião', new_food_path, class: 'btn btn-primary btn-lg' %>
      </div>
    </div>
  </div>
</section>

<div class="container">
  <div class="row">
    <div class="col-sm-4">
      One of three columns
    </div>
    <div class="col-sm-4">
      One of three columns
    </div>
    <div class="col-sm-4">
      One of three columns
    </div>
  </div>
</div>